project_id = "frectozraqrohunkniqr"

[functions.ai-travel-planner]
verify_jwt = false

[functions.weather]
verify_jwt = false

[functions.google-maps]
verify_jwt = false

[functions.ticketmaster]
verify_jwt = false

[functions.google-maps-photo]
verify_jwt = false

[functions.unsplash]
verify_jwt = false

[functions.ai-discover]
verify_jwt = false
